### ISSUE TITLE
[patch] Metaclass validity fix for LispWorks

### ISSUE THREAD

**Issue by m-lw** [marcoheisig/Petalisp#2]
The transform classes in core/transformations/invertible-transformation.lisp do not have the `funcallable-standard-class` metaclass.  Although this is compliant with AMOP, LispWorks signals an error because it leads to spurious type hierarchies (see also SBCL's AMOP Compatibility documentation).

This patch fixes it: https://gist.github.com/m-lw/e510a2b8477952dc30008c7016c159be

**Comment by marcoheisig** [comment]
Thank you for pointing that out! Isn't the MOP a fun thing :)
