### ISSUE TITLE
Minor issues when starting out with Petalisp

### ISSUE THREAD

**Issue by moneylobster** [marcoheisig/Petalisp#25]
Hello, I wanted to try out this library after watching your newest ELS talk and I've faced some small issues when getting started:

- When installing Petalisp from Quicklisp with the Ultralisp distribution enabled, I faced errors since Typo isn't on Ultralisp but Petalisp is, which means a recent version of Petalisp gets installed along with a relatively older version of Typo. I mitigated this by installing Typo manually, but you may consider adding Typo to Ultralisp to make such an installation flow smoother.

- in `examples/getting-started.lisp`:
  - `compute-list-of-arrays` in the `present` function (https://github.com/marcoheisig/Petalisp/blob/master/examples/getting-started.lisp#L17) is undefined, using `petalisp.core:compute-list-of-arrays` instead worked for me.
  - `lazy-indices` is undefined (https://github.com/marcoheisig/Petalisp/blob/master/examples/getting-started.lisp#L34), using `lazy-index-components` instead seems to give the desired output.

Thanks for your work on this repository. While I'm still familiarizing myself with the syntax and going through the examples, expressing numeric computations lazily to allow for more optimization opportunities seems like a very interesting idea.

**Comment by marcoheisig** [comment]
Fixed in f4847a2ae29721a3586f0c83a5e1338e7ce31b89, thanks for reporting!

About Ultralisp: I haven't used it so far, but adding my projects there sounds like a good idea.  The only problem is that the https://ultralisp.org website isn't reachable for me right now.  Do you know how I can add projects to Ultralisp?

**Comment by moneylobster** [comment]
Thanks for the quick fixes!  The way to register new projects onto Ultralisp is via the frontend on ultralisp.org, but I've also been experiencing outages with it recently, despite the actual distribution on dist.ultralisp.org being reachable. If you wish I can let you know when the website seems to be up again.

**Comment by moneylobster** [comment]
Just letting you know that I can currently access the Ultralisp website.

**Comment by marcoheisig** [comment]
I just added all my projects to Ultralisp.  Thanks again for reaching out!
