### ISSUE TITLE
AVX2 support added to SBCL

### ISSUE THREAD

**Issue by equwal** [marcoheisig/Petalisp#3]
https://github.com/sbcl/sbcl/commit/e98018e1dc17f3e2490399baa020c60d1319f1f4#diff-38fa048d2fea8697a7a6bb3c8e848f40
My understanding is that inline ASM is required to do anything with it.

**Comment by marcoheisig** [comment]
I wouldn't call it inline ASM.  Paul Khuong gives a good overview of sbcl's VOP mechanism in https://www.pvk.ca/Blog/2014/08/16/how-to-define-new-intrinsics-in-sbcl/ .

I will try to write some high level bindings and add them to https://github.com/guicho271828/cl-simd as soon as I have time.  Then I need to teach my new library 'restricted-functions' to detect vectorizable instructions.  And then I need to teach Petalisp about vectorization.

But I am extremely excited about avx2 in sbcl.  Feels like Christmas.

**Comment by equwal** [comment]
Well it is pretty exciting either way.

Closing this since I only wanted to alert the author about that commit to sbcl in December 2018.

**Comment by marcoheisig** [comment]
I certainly won't forget about this issue, since one of my side projects is to improve the SIMD support for SBCL :)
