### ISSUE TITLE
Many build failures 

### ISSUE THREAD

**Issue by xach** [marcoheisig/Petalisp#4]
Hi, a lot of stuff does not build in petalisp today. I made a list with build logs here:

http://report.quicklisp.org/2019-02-28/failure-report/petalisp.html

If there's any additional info I can provide to help, please let me know.

**Comment by marcoheisig** [comment]
Strange ... my CI reports no errors ... it seems 'split-sequence' was not loaded.  I'm adding it as an explicit ASDF dependency.  I hope that fixes it.

**Comment by xach** [comment]
Thank you, that fixed a lot. The last remaining system is petalisp.utilities which has an implicit dependency on alexandria. The build logs above have been updated.

**Comment by marcoheisig** [comment]
Ok, I fixed that, too.  Thank you for reporting. (And thanks for making the CL universe so awesome!)
