### ISSUE TITLE
Linear algebra example doesn't compile.

### ISSUE THREAD

**Issue by tre-flip** [marcoheisig/Petalisp#9]
Hello, I'm exploring this great library, but I'm stuck on this [example](https://github.com/marcoheisig/Petalisp/blob/master/examples/linear-algebra.lisp). 

Expected behaviour:
Copy the example to "linalg.lisp", load Petalisp and Trivia, compile "linalg.lisp".

Actual behaviour:
Petalisp and Trivia have been successfully loaded, but the example doesn't compile and produces the following [compilation error](https://gist.github.com/KnightOfTribulus/8c2c6e191e0ee9b2d54bc12b0a66ad54).

My system specification:
CL implementation: SBCL 1.4.14-3.fc31.
OS: Fedora 31, Kernel: 5.3.7-301.fc31.x86_64.

**Comment by marcoheisig** [comment]
Thanks for reporting.  Unfortunately, I cannot reproduce this issue.  But it looks similar to a Trivia problem I fixed some time ago.

Can you reproduce the problem with the most recent versions of Trivia and SBCL?

**Comment by tre-flip** [comment]
Yes, it seems to be my fault, because I'm running old software on this machine. I upgraded to the latest version on SBCL and now I can't reproduce this bug.
